# File: .github/workflows/repo-sync.yml
name: 同步上游仓库
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync 6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE.git"
          source_branch: "main"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
